name: reviewdog
on: 
  pull_request:
    branches:
      - dev
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          workdir: apps/
          eslint_flags: '. --ext .js'
          filter_mode: nofilter
          fail_on_error: true

  standard:
    name: runner / standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: |
          cd apps
          npm install
      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd apps 
          npx semistandard | reviewdog -reporter=github-pr-review -f=standardjs -filter-mode=nofilter -fail-on-error
